"""add websites monitoring and debug models

Revision ID: 004836b37ca7
Revises: 001
Create Date: 2025-10-25 03:20:21.920127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004836b37ca7'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('check_interval', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_id'), 'websites', ['id'], unique=False)
    op.create_index(op.f('ix_websites_url'), 'websites', ['url'], unique=True)
    op.create_table('debug_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debug_sessions_id'), 'debug_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_debug_sessions_start_time'), 'debug_sessions', ['start_time'], unique=False)
    op.create_index(op.f('ix_debug_sessions_website_id'), 'debug_sessions', ['website_id'], unique=False)
    op.create_table('monitoring_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('success', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_results_id'), 'monitoring_results', ['id'], unique=False)
    op.create_index(op.f('ix_monitoring_results_timestamp'), 'monitoring_results', ['timestamp'], unique=False)
    op.create_index(op.f('ix_monitoring_results_website_id'), 'monitoring_results', ['website_id'], unique=False)
    op.create_table('network_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debug_session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['debug_session_id'], ['debug_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_events_debug_session_id'), 'network_events', ['debug_session_id'], unique=False)
    op.create_index(op.f('ix_network_events_id'), 'network_events', ['id'], unique=False)
    op.create_index(op.f('ix_network_events_timestamp'), 'network_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_network_events_timestamp'), table_name='network_events')
    op.drop_index(op.f('ix_network_events_id'), table_name='network_events')
    op.drop_index(op.f('ix_network_events_debug_session_id'), table_name='network_events')
    op.drop_table('network_events')
    op.drop_index(op.f('ix_monitoring_results_website_id'), table_name='monitoring_results')
    op.drop_index(op.f('ix_monitoring_results_timestamp'), table_name='monitoring_results')
    op.drop_index(op.f('ix_monitoring_results_id'), table_name='monitoring_results')
    op.drop_table('monitoring_results')
    op.drop_index(op.f('ix_debug_sessions_website_id'), table_name='debug_sessions')
    op.drop_index(op.f('ix_debug_sessions_start_time'), table_name='debug_sessions')
    op.drop_index(op.f('ix_debug_sessions_id'), table_name='debug_sessions')
    op.drop_table('debug_sessions')
    op.drop_index(op.f('ix_websites_url'), table_name='websites')
    op.drop_index(op.f('ix_websites_id'), table_name='websites')
    op.drop_table('websites')
    # ### end Alembic commands ###
