"""add monitoring models

Revision ID: 1a96e5049f0d
Revises: 001
Create Date: 2025-10-25 00:45:07.811386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a96e5049f0d'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('check_interval', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_websites_active_url', 'websites', ['is_active', 'url'], unique=False)
    op.create_index(op.f('ix_websites_id'), 'websites', ['id'], unique=False)
    op.create_index(op.f('ix_websites_is_active'), 'websites', ['is_active'], unique=False)
    op.create_index(op.f('ix_websites_url'), 'websites', ['url'], unique=True)
    op.create_table('debug_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('browser_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debug_sessions_id'), 'debug_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_debug_sessions_session_key'), 'debug_sessions', ['session_key'], unique=True)
    op.create_index(op.f('ix_debug_sessions_started_at'), 'debug_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_debug_sessions_website_id'), 'debug_sessions', ['website_id'], unique=False)
    op.create_index('ix_debug_sessions_website_started', 'debug_sessions', ['website_id', 'started_at'], unique=False)
    op.create_table('downtime_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('initial_status', sa.Enum('UP', 'DOWN', 'DEGRADED', 'UNKNOWN', name='monitorstatus'), nullable=False),
    sa.Column('recovery_status', sa.Enum('UP', 'DOWN', 'DEGRADED', 'UNKNOWN', name='monitorstatus'), nullable=True),
    sa.Column('affected_checks_count', sa.Integer(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downtime_windows_ended_at'), 'downtime_windows', ['ended_at'], unique=False)
    op.create_index(op.f('ix_downtime_windows_id'), 'downtime_windows', ['id'], unique=False)
    op.create_index('ix_downtime_windows_ongoing', 'downtime_windows', ['website_id', 'ended_at'], unique=False)
    op.create_index(op.f('ix_downtime_windows_started_at'), 'downtime_windows', ['started_at'], unique=False)
    op.create_index(op.f('ix_downtime_windows_website_id'), 'downtime_windows', ['website_id'], unique=False)
    op.create_index('ix_downtime_windows_website_started', 'downtime_windows', ['website_id', 'started_at'], unique=False)
    op.create_table('monitor_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UP', 'DOWN', 'DEGRADED', 'UNKNOWN', name='monitorstatus'), nullable=False),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('http_method', sa.Enum('GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', 'OPTIONS', name='httpmethod'), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('dns_time_ms', sa.Float(), nullable=True),
    sa.Column('connect_time_ms', sa.Float(), nullable=True),
    sa.Column('tls_time_ms', sa.Float(), nullable=True),
    sa.Column('ttfb_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_checks_checked_at'), 'monitor_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_monitor_checks_id'), 'monitor_checks', ['id'], unique=False)
    op.create_index('ix_monitor_checks_status_checked', 'monitor_checks', ['status', 'checked_at'], unique=False)
    op.create_index('ix_monitor_checks_website_checked', 'monitor_checks', ['website_id', 'checked_at'], unique=False)
    op.create_index(op.f('ix_monitor_checks_website_id'), 'monitor_checks', ['website_id'], unique=False)
    op.create_table('network_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debug_session_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('REQUEST', 'RESPONSE', 'ERROR', 'REDIRECT', 'TIMEOUT', name='networkeventtype'), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', 'OPTIONS', name='httpmethod'), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('request_headers', sa.Text(), nullable=True),
    sa.Column('response_headers', sa.Text(), nullable=True),
    sa.Column('request_payload', sa.Text(), nullable=True),
    sa.Column('response_payload', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['debug_session_id'], ['debug_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_events_debug_session_id'), 'network_events', ['debug_session_id'], unique=False)
    op.create_index(op.f('ix_network_events_event_type'), 'network_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_network_events_id'), 'network_events', ['id'], unique=False)
    op.create_index('ix_network_events_session_timestamp', 'network_events', ['debug_session_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_network_events_timestamp'), 'network_events', ['timestamp'], unique=False)
    op.create_index('ix_network_events_type_timestamp', 'network_events', ['event_type', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_network_events_type_timestamp', table_name='network_events')
    op.drop_index(op.f('ix_network_events_timestamp'), table_name='network_events')
    op.drop_index('ix_network_events_session_timestamp', table_name='network_events')
    op.drop_index(op.f('ix_network_events_id'), table_name='network_events')
    op.drop_index(op.f('ix_network_events_event_type'), table_name='network_events')
    op.drop_index(op.f('ix_network_events_debug_session_id'), table_name='network_events')
    op.drop_table('network_events')
    op.drop_index(op.f('ix_monitor_checks_website_id'), table_name='monitor_checks')
    op.drop_index('ix_monitor_checks_website_checked', table_name='monitor_checks')
    op.drop_index('ix_monitor_checks_status_checked', table_name='monitor_checks')
    op.drop_index(op.f('ix_monitor_checks_id'), table_name='monitor_checks')
    op.drop_index(op.f('ix_monitor_checks_checked_at'), table_name='monitor_checks')
    op.drop_table('monitor_checks')
    op.drop_index('ix_downtime_windows_website_started', table_name='downtime_windows')
    op.drop_index(op.f('ix_downtime_windows_website_id'), table_name='downtime_windows')
    op.drop_index(op.f('ix_downtime_windows_started_at'), table_name='downtime_windows')
    op.drop_index('ix_downtime_windows_ongoing', table_name='downtime_windows')
    op.drop_index(op.f('ix_downtime_windows_id'), table_name='downtime_windows')
    op.drop_index(op.f('ix_downtime_windows_ended_at'), table_name='downtime_windows')
    op.drop_table('downtime_windows')
    op.drop_index('ix_debug_sessions_website_started', table_name='debug_sessions')
    op.drop_index(op.f('ix_debug_sessions_website_id'), table_name='debug_sessions')
    op.drop_index(op.f('ix_debug_sessions_started_at'), table_name='debug_sessions')
    op.drop_index(op.f('ix_debug_sessions_session_key'), table_name='debug_sessions')
    op.drop_index(op.f('ix_debug_sessions_id'), table_name='debug_sessions')
    op.drop_table('debug_sessions')
    op.drop_index(op.f('ix_websites_url'), table_name='websites')
    op.drop_index(op.f('ix_websites_is_active'), table_name='websites')
    op.drop_index(op.f('ix_websites_id'), table_name='websites')
    op.drop_index('ix_websites_active_url', table_name='websites')
    op.drop_table('websites')
    # ### end Alembic commands ###
