"""add_website_monitoring_models

Revision ID: a52eb8fd382e
Revises: 001
Create Date: 2025-10-25 02:41:36.653924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a52eb8fd382e'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('check_interval', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_id'), 'websites', ['id'], unique=False)
    op.create_index(op.f('ix_websites_url'), 'websites', ['url'], unique=True)
    op.create_table('downtime_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downtime_windows_end_time'), 'downtime_windows', ['end_time'], unique=False)
    op.create_index(op.f('ix_downtime_windows_id'), 'downtime_windows', ['id'], unique=False)
    op.create_index(op.f('ix_downtime_windows_start_time'), 'downtime_windows', ['start_time'], unique=False)
    op.create_index(op.f('ix_downtime_windows_website_id'), 'downtime_windows', ['website_id'], unique=False)
    op.create_table('monitor_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_checks_id'), 'monitor_checks', ['id'], unique=False)
    op.create_index(op.f('ix_monitor_checks_timestamp'), 'monitor_checks', ['timestamp'], unique=False)
    op.create_index(op.f('ix_monitor_checks_website_id'), 'monitor_checks', ['website_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitor_checks_website_id'), table_name='monitor_checks')
    op.drop_index(op.f('ix_monitor_checks_timestamp'), table_name='monitor_checks')
    op.drop_index(op.f('ix_monitor_checks_id'), table_name='monitor_checks')
    op.drop_table('monitor_checks')
    op.drop_index(op.f('ix_downtime_windows_website_id'), table_name='downtime_windows')
    op.drop_index(op.f('ix_downtime_windows_start_time'), table_name='downtime_windows')
    op.drop_index(op.f('ix_downtime_windows_id'), table_name='downtime_windows')
    op.drop_index(op.f('ix_downtime_windows_end_time'), table_name='downtime_windows')
    op.drop_table('downtime_windows')
    op.drop_index(op.f('ix_websites_url'), table_name='websites')
    op.drop_index(op.f('ix_websites_id'), table_name='websites')
    op.drop_table('websites')
    # ### end Alembic commands ###
