"""add monitoring models for sla analytics

Revision ID: d98cc6138310
Revises: 001
Create Date: 2025-10-26 12:36:16.856013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98cc6138310'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('check_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitors_id'), 'monitors', ['id'], unique=False)
    op.create_table('downtime_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downtime_windows_ended_at'), 'downtime_windows', ['ended_at'], unique=False)
    op.create_index(op.f('ix_downtime_windows_id'), 'downtime_windows', ['id'], unique=False)
    op.create_index('ix_downtime_windows_monitor_started', 'downtime_windows', ['monitor_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_downtime_windows_started_at'), 'downtime_windows', ['started_at'], unique=False)
    op.create_table('monitor_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('is_up', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_checks_checked_at'), 'monitor_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_monitor_checks_id'), 'monitor_checks', ['id'], unique=False)
    op.create_index('ix_monitor_checks_monitor_checked', 'monitor_checks', ['monitor_id', 'checked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_monitor_checks_monitor_checked', table_name='monitor_checks')
    op.drop_index(op.f('ix_monitor_checks_id'), table_name='monitor_checks')
    op.drop_index(op.f('ix_monitor_checks_checked_at'), table_name='monitor_checks')
    op.drop_table('monitor_checks')
    op.drop_index(op.f('ix_downtime_windows_started_at'), table_name='downtime_windows')
    op.drop_index('ix_downtime_windows_monitor_started', table_name='downtime_windows')
    op.drop_index(op.f('ix_downtime_windows_id'), table_name='downtime_windows')
    op.drop_index(op.f('ix_downtime_windows_ended_at'), table_name='downtime_windows')
    op.drop_table('downtime_windows')
    op.drop_index(op.f('ix_monitors_id'), table_name='monitors')
    op.drop_table('monitors')
    # ### end Alembic commands ###
